
server:
  port: 8080
logging:
  level.org.springframework.web: error
  level.com.yjw.exam.controller: error
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    ##数据库的连接端口和数据库名称
    url: jdbc:mysql://localhost:3306/b2c?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mybatis-plus:
    ##实体类的位置
    type-aliases-package: com.yjw.exam.entity
    ###MySQL语句的位置
    mapper-locations: classpath:/mapper/b2c/*.xml
    #打印sql语句
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html

  logging:
    level:
      com.yjw.shop.b2c.mapper: info
      com.ltsolution.framework.bs.system.mapper: debug


